FORMAT: 1A
HOST: https://kapi-test.herokuapp.com

# kapi

Kapi是內部開發所使用的.

## 咖啡店 [/cafes{?limited_time}{?socket}{?standing_desk}{?mrt}{?city}]

### GET [GET]

可以取得咖啡店資料
+ Parameters
    + limited_time (optional,number) - 限制時間
    + socket (optional,number) - 插座
    + standing_desk (optional,number) - 站立位
    + mrt (optional,string) - 捷運站
    + city (optional,string) - 城市
+ Request 
    + Headers()
            token: eyJhbGciOiJIUzI1NiIsImlhdCI6MTQ5MjA4OTY2MCwiZXhwIjoxNDk0NzY4MDYwfQ.eyJpZCI6IjJjZmI2MDY1LWM1NTEtNDVkYy1iYjA0LTBmOGUyNTJjN2ViOSJ9.tvt3G1qgooHD3LoetN6Zc2c3Z256YbbrnlibbEHQjlo
+ Response 200 (application/json)

        [
            {
                "id": "00014645-38c8-4eb4-ad9b-faa871d7e511",
                "address": "\u5609\u7fa9\u5e02\u6771\u5340\u5fe0\u5b5d\u8def205\u865f",
                "name": "R5\u5c0f\u9910\u9928",
                "phone": "052770250",
                "city": "chiayi",
                "latitude": 23.4838654,
                "longitude": 120.4535834,
                "standing_desk": 2
                "socket": 3,
                "limited_time": 3,
                "url": null,
                "fb_url": "https://www.facebook.com/r5.bistro",
                "mrt": null,
                "business_hour": {
                    "sun_1_open": "11:30",
                    "wed_1_open": "11:30",
                    "sat_1_open": "11:30",
                    "sun_1_close": "21:00",
                    "thu_1_open": "11:30",
                    "mon_1_open": "11:30",
                    "wed_1_close": "21:00",
                    "sat_1_close": "21:00",
                    "tue_1_open": "11:30",
                    "thu_1_close": "21:00",
                    "fri_1_close": "21:00",
                    "mon_1_close": "21:00",
                    "fri_1_open": "11:30",
                    "tue_1_close": "21:00"
                },
                "tags": null,
                "rates": {
                    "seat": 5.0,
                    "food": null,
                    "average": 5.0,
                    "wifi": 5.0,
                    "quiet": 5.0,
                    "tasty": 5.0,
                    "music": 5.0,
                    "cheap": 5.0
                },
                "photos": {
                    "google_s": "https://maps.googleapis.com/maps/api/place/photo?xxxx",
                    "google_l": "https://maps.googleapis.com/maps/api/place/photo?xxxx"
                },
                "is_kapi": false,
            },
            …
        ]

### POST [POST]
可以新增咖啡店資料
+ Request 
    + Headers
            Content-Type: multipart/form-data
            token: eyJhbGciOiJIUzI1NiIsImlhdCI6MTQ5MjA4OTY2MCwiZXhwIjoxNDk0NzY4MDYwfQ.eyJpZCI6IjJjZmI2MDY1LWM1NTEtNDVkYy1iYjA0LTBmOGUyNTJjN2ViOSJ9.tvt3G1qgooHD3LoetN6Zc2c3Z256YbbrnlibbEHQjlo
    + Attributes(object)
        + name:  咖啡店名子(string, required)
        + address: 忠孝東路(string, required)
        + city: taipei (string, required)
        + latitude: 23.4828654 (number, required)
        + longitude: 120.4535834 (number, required)
        + id: uuid (string) - 為uuid格式，不填時自動產生
        + url: www.xxx.com (string) - 官網的url
        + fb_url: www.facebook.com/123456 (string) - Facebook的url
        + limited_time: 4 (string) - 限制時間 (1:很多,2:很少,3:看狀況,4:沒設定)
        + socket: 4 (string) - 插座 (1:很多,2:很少,3:看狀況,4:沒設定)
        + standing_desk: 4 (string) - 站立位 (1:很多,2:很少,3:看狀況,4:沒設定)
        + mrt: 4 (string) - 捷運站
        + phone: 23456789 (string) - 電話號碼
        + created_date: 1415203908 (string) - Time stamp 去掉小數點部分
    + Body
    
        {
            "name":"有間咖啡廳",
            "address":"忠孝東路",
            "city":"taipei",
            "latitude":23.4838654,
            "longitude":120.4535834,
            "url":"",
            "fb_url": "",
            "limited_time": "4",
            "socket": "4",
            "standing_desk": "2",
            "mrt": "忠孝敦化",
            "phone": "21213456",
            "created_date": "1492489712"
        }
+ Response 201 (application/json)

    + Body
    
        {
            "result": true,
            "data": {
                "id": "4a24c511-d78f-4814-84c0-1ff0e4feb890",
                "name": "\u6709\u9593\u5496\u5561\u5ef3",
                "address": "\u5fe0\u5b5d\u6771\u8def",
                "latitude": 23.4838654,
                "longitude": 120.4535834,
                "url": "",
                "fb_url": "",
                "limited_time": 4,
                "socket": 4,
                "standing_desk": 2,
                "mrt": "",
                "city": "taipei",
                "phone": "",
                "created_date": 1492489712,
                "is_kapi": true
            }
        }